## Proxy used for connecting to exchange APIs, supporting http and socks5 proxies
# proxy: socks5://localhost:1080
# proxy: http://localhost:7777
# proxy: https://localhost:7777

## Auto refresh on every specified seconds, note every exchange has a rate limit,
## too frequent refresh may cause your IP banned by their server
#refresh: 10

## HTTP request timeout (in seconds)
# timeout: 20

## Running in debug mode
# debug: true

# Specify columns to show
# show:
# - Symbol
# - Price
# - "%Change(1h)"
# - "%Change(24h)"
# - Source
# - Updated

exchanges:
  ## Exchanges are identified by name, following are supported exchanges
  - name: CoinMarketCap
    tokens:
    ## Tokens supported by this exchange, note that different exchanges have different
    ## formats to denote their tokens/markets, refer to their URLs to find the format
    #  - BTC
    #  - ETH
    #  - LTC
    api_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

  - name: Bitfinex
    tokens:
      - btcusd

  - name: Binance
    tokens:
      ## Tokens in Binance are actually token-currency pairs
      - BNBUSDT
  #  - BTCUSDT
  # - ETHUSDT
  #  - EOSETH

  - name: Huobi
    tokens:
      - HTUSDT

  - name: ZB
    tokens:
      - ZB_QC

  - name: OKEx
    tokens:
      - okb_usdt

  - name: Gate
    tokens:
      - btc_usdt

  - name: Bittrex
    tokens:
      - USDT-BTC

  - name: HitBTC
    tokens:
      - BTCUSD

  #- name: BigONE
  #  tokens:
  #  - BIG-BTC

  - name: Poloniex
    tokens:
      - BTC_ETH

  - name: Kraken
    tokens:
      - EOSETH

  - name: Coinbase
    tokens:
      - BTC-USD
